"""Audit checkpoints: manifests, durability, locking and what is *not* offered.

Every test runs against a fixture root: no real disk, boot partition, GRUB or
package manager is involved. The interruption tests fail one durable write at a
time and then assert that nothing partial survives.
"""
import contextlib
import io
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest import mock

from aios import checkpoint as checkpoint_module
from aios import durable
from aios.checkpoint import CheckpointError, Checkpoints

RELEASE = "6.18.52-0-lts"
HARDWARE_ATOMS = ("linux-firmware-intel", "wireless-regdb", "iw")
PACKAGES = {"alpine-base": "3.23.5-r0", "mesa-dri-gallium": "25.2.7-r0",
            "xorg-server": "21.1.20-r0", "linux-firmware-intel": "20251125-r1",
            "wireless-regdb": "2025.07.10-r0", "iw": "6.17-r0"}

GRUB_CONFIG = "boot/grub/grub.cfg"
GRUB_CUSTOM = "boot/grub/custom.cfg"
CUSTOM = """\
# Managed by AIOS. Regenerated by aios-install; edits are not preserved.
menuentry "AIOS recovery (safe graphics)" {
	linux /boot/vmlinuz-lts root=UUID=1111 rw quiet aios.recovery nomodeset
	initrd /boot/initramfs-lts
}
"""

POSIX = unittest.skipUnless(os.name == "posix", "the checkpoint store needs POSIX locking")

# User state the checkpoint surface must never read or write.
USER_FILES = {
    "home/aios/.local/share/aios/chats.json": '{"chats": ["private"]}',
    "home/aios/.local/state/aios/renderer.json": '{"status": "ready"}',
    "var/lib/aios/models/qwen.gguf": "model-weights",
}


def build_system(root, mode="installed", kernel=b"kernel-a", initramfs=b"initramfs-a"):
    """A fixture installed system the checkpoint helper can record."""
    root = Path(root)
    for relative, text in (("etc/aios-mode", mode + "\n"),
                           ("etc/alpine-release", "3.23.5\n"),
                           ("usr/local/share/aios/world.hardware",
                            "\n".join(HARDWARE_ATOMS) + "\n")):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    database = root / "lib" / "apk" / "db"
    database.mkdir(parents=True)
    (database / "installed").write_text(
        "\n\n".join(f"P:{name}\nV:{version}" for name, version in sorted(PACKAGES.items())) + "\n")
    modules = root / "lib" / "modules" / RELEASE / "kernel" / "drivers"
    modules.mkdir(parents=True)
    (modules / "iwlwifi.ko.gz").write_bytes(b"module-bytes")
    boot = root / "boot"
    boot.mkdir(parents=True, exist_ok=True)
    (boot / "vmlinuz-lts").write_bytes(kernel)
    (boot / "initramfs-lts").write_bytes(initramfs)
    (root / "boot" / "grub").mkdir(parents=True)
    (root / GRUB_CONFIG).write_text("menuentry 'AIOS' {\n linux /boot/vmlinuz-lts\n}\n")
    (root / GRUB_CUSTOM).write_text(CUSTOM)
    for relative, text in USER_FILES.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return root


def user_state(root):
    return {relative: (Path(root) / relative).read_text() for relative in USER_FILES}


def boot_state(root):
    return {relative: (Path(root) / relative).read_bytes()
            for relative in ("boot/vmlinuz-lts", "boot/initramfs-lts",
                             GRUB_CONFIG, GRUB_CUSTOM)}


class ManifestTests(unittest.TestCase):
    """Identifiers are derived from content, never supplied."""

    def setUp(self):
        workspace = tempfile.TemporaryDirectory(prefix="aios-checkpoint-manifest-")
        self.addCleanup(workspace.cleanup)
        self.root = build_system(workspace.name)
        self.checkpoints = Checkpoints(self.root)

    def test_the_manifest_records_one_release_family_and_the_whole_closure(self):
        manifest = self.checkpoints.describe_running_system()
        self.assertEqual(manifest["kind"], "aios-checkpoint-manifest")
        self.assertEqual(manifest["alpine_branch"], "v3.23")
        self.assertEqual(manifest["kernel_release"], RELEASE)
        self.assertEqual(sorted(manifest["hardware_packages"]), sorted(HARDWARE_ATOMS))
        self.assertEqual(manifest["graphics_packages"],
                         {"mesa-dri-gallium": "25.2.7-r0", "xorg-server": "21.1.20-r0"})
        self.assertEqual(sorted(manifest["artifacts"]), ["initramfs", "vmlinuz"])
        self.assertEqual(manifest["package_count"], len(PACKAGES))
        self.assertEqual(manifest["module_count"], 1)
        self.assertTrue(manifest["physical_revalidation_required"])
        self.assertFalse(manifest["restorable"])

    def test_the_identifier_is_the_digest_of_the_recorded_content(self):
        manifest = self.checkpoints.describe_running_system()
        content = {key: value for key, value in manifest.items()
                   if key not in ("checkpoint_id", "created", "physical_revalidation_required",
                                  "restorable")}
        self.assertEqual(manifest["checkpoint_id"], checkpoint_module.derive_id(content))
        self.assertEqual(len(manifest["checkpoint_id"]), 64)
        again = self.checkpoints.describe_running_system()
        self.assertEqual(again["checkpoint_id"], manifest["checkpoint_id"])

    def test_changing_any_recorded_input_changes_the_identifier(self):
        original = self.checkpoints.describe_running_system()["checkpoint_id"]
        (Path(self.root) / "boot" / "vmlinuz-lts").write_bytes(b"different-kernel")
        self.assertNotEqual(self.checkpoints.describe_running_system()["checkpoint_id"], original)

    def test_a_module_edited_without_changing_its_size_changes_the_identifier(self):
        original = self.checkpoints.describe_running_system()["modules_inventory_digest"]
        module = Path(self.root) / "lib/modules" / RELEASE / "kernel/drivers/iwlwifi.ko.gz"
        module.write_bytes(b"module-bytez")
        self.assertEqual(len(module.read_bytes()), len(b"module-bytes"))
        self.assertNotEqual(
            self.checkpoints.describe_running_system()["modules_inventory_digest"], original)

    def test_a_free_form_identifier_is_refused(self):
        for value in ("latest", "../../etc/passwd", "", "Z" * 64, "a" * 63, None, 5,
                      "/var/lib/aios/checkpoints/x"):
            with self.assertRaises(CheckpointError):
                checkpoint_module.validate_id(value)

    def test_an_incomplete_hardware_closure_refuses_to_produce_a_manifest(self):
        database = Path(self.root) / "lib/apk/db/installed"
        database.write_text(database.read_text().replace("P:wireless-regdb", "P:other"))
        with self.assertRaises(CheckpointError):
            self.checkpoints.describe_running_system()


@POSIX
class StagingTests(unittest.TestCase):
    """Recording is durable, space-checked and never half-valid."""

    def setUp(self):
        workspace = tempfile.TemporaryDirectory(prefix="aios-checkpoint-stage-")
        self.addCleanup(workspace.cleanup)
        self.root = build_system(workspace.name)
        self.checkpoints = Checkpoints(self.root)

    def store(self):
        return Path(self.root) / checkpoint_module.STORE_ROOT

    def test_recording_stores_the_running_system_and_is_idempotent(self):
        result = self.checkpoints.stage()
        checkpoint_id = result["checkpoint_id"]
        self.assertTrue(result["staged"])
        self.assertFalse(result["restorable"])
        directory = self.store() / checkpoint_id
        self.assertEqual((directory / "vmlinuz").read_bytes(),
                         (Path(self.root) / "boot/vmlinuz-lts").read_bytes())
        self.assertTrue(self.checkpoints.verify_artifacts(checkpoint_id)["artifacts_verified"])
        again = self.checkpoints.stage()
        self.assertFalse(again["staged"])
        self.assertTrue(again["already_recorded"])
        self.assertEqual(again["checkpoint_id"], checkpoint_id)

    def test_nothing_under_boot_or_grub_is_ever_written(self):
        before = boot_state(self.root)
        self.checkpoints.stage()
        self.checkpoints.verify()
        self.assertEqual(boot_state(self.root), before)
        self.assertFalse((Path(self.root) / "boot" / "aios").exists())

    def test_user_state_is_untouched(self):
        before = user_state(self.root)
        self.checkpoints.stage()
        self.checkpoints.status()
        self.checkpoints.verify()
        self.assertEqual(user_state(self.root), before)

    def test_a_live_session_refuses_to_record(self):
        live = Checkpoints(build_system(tempfile.mkdtemp(prefix="aios-live-"), mode="live"))
        with self.assertRaises(CheckpointError) as raised:
            live.stage()
        self.assertIn("installed system", str(raised.exception))

    def test_recording_refuses_without_enough_free_space(self):
        with mock.patch.object(checkpoint_module, "free_space_bytes", return_value=1024):
            with self.assertRaises(CheckpointError) as raised:
                self.checkpoints.stage()
        self.assertIn("free space", str(raised.exception))
        self.assertEqual(self.checkpoints.recorded_ids(), [])

    def test_an_interrupted_copy_leaves_no_valid_checkpoint(self):
        real = checkpoint_module.copy_durable
        calls = []

        def failing(source, destination, **keywords):
            calls.append(destination)
            if len(calls) > 1:
                raise OSError(28, "No space left on device")
            return real(source, destination, **keywords)

        with mock.patch.object(checkpoint_module, "copy_durable", failing):
            with self.assertRaises(OSError):
                self.checkpoints.stage()
        self.assertEqual(self.checkpoints.recorded_ids(), [])
        self.assertEqual([entry.name for entry in self.store().iterdir()
                          if entry.is_dir()], [])

    def test_an_interrupted_manifest_write_leaves_no_valid_checkpoint(self):
        with mock.patch.object(checkpoint_module, "write_atomic",
                               side_effect=OSError(5, "I/O error")):
            with self.assertRaises(OSError):
                self.checkpoints.stage()
        self.assertEqual(self.checkpoints.recorded_ids(), [])
        self.assertEqual(self.checkpoints.status()["recorded"], 0)

    def test_a_readback_mismatch_removes_what_was_just_written(self):
        with mock.patch.object(Checkpoints, "verify_artifacts",
                               return_value={"artifacts_verified": False,
                                             "mismatched_artifacts": ["vmlinuz"]}):
            with self.assertRaises(CheckpointError):
                self.checkpoints.stage()
        self.assertEqual([entry.name for entry in self.store().iterdir() if entry.is_dir()], [])

    def test_leftovers_from_an_interrupted_run_are_reclaimed(self):
        store = self.store()
        store.mkdir(parents=True, exist_ok=True)
        orphan = store / ("b" * 64)
        orphan.mkdir()
        (orphan / "vmlinuz").write_bytes(b"partial")
        nested = orphan / f"{durable.TEMP_PREFIX}99-initramfs"
        nested.write_bytes(b"partial")
        stray = store / f"{durable.TEMP_PREFIX}99-manifest.json"
        stray.write_text("{}")
        unnamed = store / "scratch"
        unnamed.mkdir()
        result = self.checkpoints.stage()
        self.assertTrue(result["staged"])
        self.assertIn(stray.name, result["removed_temporaries"])
        self.assertIn(orphan.name, result["removed_incomplete"])
        self.assertIn("scratch", result["removed_incomplete"])
        self.assertFalse(orphan.exists())
        self.assertFalse(unnamed.exists())
        self.assertEqual(self.checkpoints.recorded_ids(), [result["checkpoint_id"]])

    def test_a_manifest_that_no_longer_matches_its_content_is_not_a_checkpoint(self):
        checkpoint_id = self.checkpoints.stage()["checkpoint_id"]
        path = self.checkpoints.manifest_path(checkpoint_id)
        manifest = json.loads(path.read_text())
        manifest["kernel_release"] = "9.9.9-0-lts"
        path.write_text(json.dumps(manifest))
        with self.assertRaises(CheckpointError):
            self.checkpoints.read_manifest(checkpoint_id)
        self.assertIn("error", self.checkpoints.status()["checkpoints"][0])

    def test_two_concurrent_recordings_cannot_interleave(self):
        holder = durable.exclusive_lock(self.store())
        holder.__enter__()
        self.addCleanup(lambda: holder.__exit__(None, None, None))
        with self.assertRaises(CheckpointError) as raised:
            self.checkpoints.stage()
        self.assertIn("already running", str(raised.exception))
        self.assertEqual(self.checkpoints.recorded_ids(), [])

    def test_the_lock_is_released_for_the_next_operation(self):
        first = self.checkpoints.stage()["checkpoint_id"]
        (Path(self.root) / "boot" / "vmlinuz-lts").write_bytes(b"kernel-b")
        second = self.checkpoints.stage()["checkpoint_id"]
        self.assertNotEqual(first, second)
        self.assertEqual(len(self.checkpoints.recorded_ids()), 2)

    def test_the_lock_file_is_owner_only(self):
        self.checkpoints.stage()
        mode = (self.store() / durable.LOCK_NAME).stat().st_mode & 0o777
        self.assertEqual(mode, 0o600)


@POSIX
class VerificationTests(unittest.TestCase):
    """Verification re-reads the stored snapshot and nothing else."""

    def setUp(self):
        workspace = tempfile.TemporaryDirectory(prefix="aios-checkpoint-verify-")
        self.addCleanup(workspace.cleanup)
        self.root = build_system(workspace.name)
        self.checkpoints = Checkpoints(self.root)
        self.checkpoint_id = self.checkpoints.stage()["checkpoint_id"]

    def test_an_untouched_checkpoint_verifies(self):
        report = self.checkpoints.verify()
        self.assertTrue(report["verified"])
        self.assertEqual(report["verification"][0]["checkpoint_id"], self.checkpoint_id)

    def test_a_tampered_artifact_fails_verification(self):
        stored = Path(self.root) / checkpoint_module.STORE_ROOT / self.checkpoint_id / "vmlinuz"
        stored.write_bytes(b"kernel-x")
        report = self.checkpoints.verify()
        self.assertFalse(report["verified"])
        self.assertEqual(report["verification"][0]["mismatched_artifacts"], ["vmlinuz"])

    def test_verification_says_nothing_about_restoring_anything(self):
        report = self.checkpoints.verify()
        for flag in ("activation_enabled", "rollback_enabled", "package_acquisition_enabled"):
            self.assertFalse(report[flag], flag)


@POSIX
class StatusTests(unittest.TestCase):
    """Status states what is recorded and what is deliberately not possible."""

    def setUp(self):
        workspace = tempfile.TemporaryDirectory(prefix="aios-checkpoint-status-")
        self.addCleanup(workspace.cleanup)
        self.root = build_system(workspace.name)
        self.checkpoints = Checkpoints(self.root)

    def test_status_reports_every_disabled_capability_explicitly(self):
        report = self.checkpoints.status()
        self.assertEqual(report["kind"], "aios-checkpoint-status")
        self.assertFalse(report["activation_enabled"])
        self.assertFalse(report["rollback_enabled"])
        self.assertFalse(report["package_acquisition_enabled"])
        self.assertIn("full-system snapshot", report["capability_note"])
        self.assertIn("signed package bundle", report["capability_note"])

    def test_status_is_sanitized_and_carries_no_device_or_user_data(self):
        self.checkpoints.stage()
        text = json.dumps(self.checkpoints.status())
        self.assertNotIn(str(self.root), text)
        self.assertNotIn("/dev/", text)
        self.assertNotIn("chats.json", text)
        entry = self.checkpoints.status()["checkpoints"][0]
        self.assertEqual(entry["kernel_release"], RELEASE)
        self.assertFalse(entry["restorable"])
        self.assertTrue(entry["physical_revalidation_required"])

    def test_a_live_session_can_still_be_inspected(self):
        live = Checkpoints(build_system(tempfile.mkdtemp(prefix="aios-live-status-"), mode="live"))
        self.assertEqual(live.status()["mode"], "live")
        self.assertEqual(live.status()["recorded"], 0)


class SurfaceTests(unittest.TestCase):
    """The command surface offers no activation, rollback or acquisition."""

    def test_only_three_operations_exist(self):
        self.assertEqual(checkpoint_module.OPERATIONS, ("status", "verify", "stage"))
        for removed in ("activate", "rollback"):
            self.assertFalse(hasattr(Checkpoints, removed), removed)

    def test_unknown_operations_are_rejected_by_the_parser(self):
        for argv in (["activate", "--checkpoint-id", "a" * 64], ["rollback"], ["update"]):
            with contextlib.redirect_stderr(io.StringIO()):
                with self.assertRaises(SystemExit):
                    checkpoint_module.main(argv)

    def test_the_module_contains_no_network_or_subprocess_client(self):
        source = Path(checkpoint_module.__file__).read_text(encoding="utf-8")
        for forbidden in ("import subprocess", "import urllib", "import socket", "http://",
                          "https://", "apk add", "grub-mkconfig", "set default"):
            self.assertNotIn(forbidden, source, forbidden)

    def test_the_helper_script_documents_what_it_is_not(self):
        helper = (Path(__file__).resolve().parents[1] / "distro" / "alpine" / "overlay" /
                  "usr" / "local" / "sbin" / "aios-checkpoint")
        text = helper.read_text(encoding="utf-8")
        self.assertIn("python3 -m aios.checkpoint", text)
        self.assertIn("no activation or rollback", text)
        self.assertNotIn("doas", text.replace("/etc/doas.d/aios.conf", ""))


if __name__ == "__main__":
    unittest.main()
