import gzip
import hashlib
import importlib.util
import json
import os
import subprocess
import sys
import tarfile
import tempfile
import unittest
from io import BytesIO
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / 'scripts' / 'inspect-image.py'

_spec = importlib.util.spec_from_file_location('aios_inspect_image', SCRIPT)
inspect_image = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(inspect_image)

KERNEL_VERSION = '6.6.68-0-lts'
CANONICAL_MAIN = 'https://dl-cdn.alpinelinux.org/alpine/v3.23/main'
CANONICAL_COMMUNITY = 'https://dl-cdn.alpinelinux.org/alpine/v3.23/community'


def build_cpio_newc(entries):
    """Build a minimal "newc" cpio archive: entries is [(name, bytes), ...]."""
    out = bytearray()

    def write_entry(name, data):
        name_bytes = name.encode('utf-8') + b'\x00'
        fields = [0, 0o100644, 0, 0, 1, 0, len(data), 0, 0, 0, 0, len(name_bytes), 0]
        header = b'070701' + ''.join(f'{value:08X}' for value in fields).encode('ascii')
        assert len(header) == 110
        out.extend(header)
        out.extend(name_bytes)
        out.extend(b'\x00' * ((-len(out)) % 4))
        out.extend(data)
        out.extend(b'\x00' * ((-len(out)) % 4))

    for name, data in entries:
        write_entry(name, data)
    write_entry('TRAILER!!!', b'')
    return bytes(out)


def build_apkovl(path, world, repositories, services):
    """Build a minimal AIOS apkovl tarball (see apkovl/genapkovl-aios.sh)."""
    with tarfile.open(path, 'w:gz') as archive:
        def add_file(name, content: bytes, mode=0o644):
            info = tarfile.TarInfo(name)
            info.size = len(content)
            info.mode = mode
            archive.addfile(info, BytesIO(content))

        add_file('etc/apk/world', ('\n'.join(world) + '\n').encode())
        add_file('etc/apk/repositories', ('\n'.join(repositories) + '\n').encode())
        for level, service_names in services.items():
            for service in service_names:
                info = tarfile.TarInfo(f'etc/runlevels/{level}/{service}')
                info.type = tarfile.SYMTYPE
                info.linkname = f'/etc/init.d/{service}'
                archive.addfile(info)


def coverage_fixture():
    """Minimal coverage manifest: matching PCI/USB IDs plus one absent device."""
    def entry(entry_id, bus, pci_id, usb_id, modules):
        return {
            'id': entry_id,
            'family': 'wifi',
            'bus': bus,
            'ids': {'pci_id': pci_id, 'usb_id': usb_id, 'subsystem_id': None,
                    'subsystem_id_status': 'pending_inventory'},
            'kernel_module': modules,
            'module_dependencies': ['cfg80211', 'mac80211'],
        }

    return {
        'schema_version': 2,
        'alpine_branch': 'v3.23',
        'entries': [
            entry('intel-wifi-ax210', 'pci', '8086:2725', None, ['iwlwifi', 'iwlmvm']),
            entry('mediatek-mt7921u', 'usb', None, '0e8d:7961', ['mt7921u']),
            entry('absent-device', 'pci', 'dead:beef', None, ['nosuchmod']),
        ],
    }


class CpioParsingTests(unittest.TestCase):
    def test_round_trips_paths_and_sizes(self):
        archive = build_cpio_newc([
            ('init', b'#!/bin/sh\n'),
            ('etc/mdev.conf', b'.* root:root 660\n'),
        ])
        entries = inspect_image.parse_cpio_newc(archive)
        self.assertEqual(
            sorted((entry['path'], entry['size']) for entry in entries),
            sorted([('init', 10), ('etc/mdev.conf', 17)]),
        )

    def test_stops_at_trailer_and_ignores_nothing_after(self):
        archive = build_cpio_newc([('a', b'x')]) + b'garbage-that-must-be-ignored'
        entries = inspect_image.parse_cpio_newc(archive)
        self.assertEqual([entry['path'] for entry in entries], ['a'])

    def test_rejects_unknown_magic_instead_of_guessing(self):
        with self.assertRaises(ValueError):
            inspect_image.parse_cpio_newc(b'070707' + b'0' * 200)


class ModulesAliasTests(unittest.TestCase):
    def test_parses_alias_lines_and_skips_comments(self):
        text = (
            "# auto-generated by depmod\n"
            "alias pci:v00008086d00002725sv*sd*bc*sc*i* iwlwifi\n"
            "alias pci:v000014C3d00007961sv*sd*bc*sc*i* mt7921e\n"
            "\n"
        )
        entries = inspect_image.parse_modules_alias(text)
        self.assertEqual(len(entries), 2)
        self.assertEqual(entries[0]['module'], 'iwlwifi')
        self.assertEqual(entries[1]['module'], 'mt7921e')


class ModaliasProbeTests(unittest.TestCase):
    def test_pci_probe_wildcards_subsystem_and_class(self):
        probe = inspect_image.pci_modalias_probe('8086:2725')
        self.assertEqual(probe, 'pci:v00008086d00002725sv*sd*bc*sc*i*')

    def test_usb_probe_wildcards_version_and_interface(self):
        probe = inspect_image.usb_modalias_probe('0e8d:7961')
        self.assertEqual(probe, 'usb:v0E8Dp7961d*dc*dsc*dp*ic*isc*ip*in*')

    def test_matching_is_case_insensitive(self):
        probe = inspect_image.pci_modalias_probe('8086:2725')
        self.assertTrue(inspect_image.alias_matches_probe(
            'pci:v00008086d00002725sv*sd*bc*sc*i*', probe))
        self.assertTrue(inspect_image.alias_matches_probe(
            'PCI:V00008086D00002725SV*SD*BC*SC*I*', probe))

    def test_vendor_wildcard_alias_matches_concrete_device(self):
        probe = inspect_image.pci_modalias_probe('8086:2725')
        self.assertTrue(inspect_image.alias_matches_probe(
            'pci:v00008086d*sv*sd*bc*sc*i*', probe))

    def test_subsystem_specific_alias_still_matches_a_vendor_device_probe(self):
        probe = inspect_image.pci_modalias_probe('8086:2725')
        self.assertTrue(inspect_image.alias_matches_probe(
            'pci:v00008086d00002725sv00008086sd00000024bc*sc*i*', probe))

    def test_unrelated_device_does_not_match(self):
        probe = inspect_image.pci_modalias_probe('dead:beef')
        self.assertFalse(inspect_image.alias_matches_probe(
            'pci:v00008086d00002725sv*sd*bc*sc*i*', probe))

    def test_usb_alias_matching(self):
        probe = inspect_image.usb_modalias_probe('0e8d:7961')
        self.assertTrue(inspect_image.alias_matches_probe(
            'usb:v0E8Dp7961d*dc*dsc*dp*icFFisc*ip*in*', probe))
        self.assertFalse(inspect_image.alias_matches_probe(
            'usb:v0E8Dp7662d*dc*dsc*dp*ic*isc*ip*in*', probe))


class CoverageExpectationTests(unittest.TestCase):
    def test_modules_and_devices_come_from_the_manifest_not_a_hardcoded_list(self):
        expectations = inspect_image.coverage_expectations(coverage_fixture())
        self.assertIn('iwlwifi', expectations['modules'])
        self.assertIn('nosuchmod', expectations['modules'])
        self.assertIn('cfg80211', expectations['modules'])
        device_ids = {device['device_id'] for device in expectations['devices']}
        self.assertEqual(device_ids, {'8086:2725', '0e8d:7961', 'dead:beef'})

    def test_repository_coverage_manifest_is_usable(self):
        manifest = json.loads(
            (ROOT / 'docs' / 'qa' / 'hardware-coverage.json').read_text(encoding='utf-8'))
        expectations = inspect_image.coverage_expectations(manifest)
        self.assertGreater(len(expectations['devices']), 10)
        self.assertIn('i915', expectations['modules'])
        self.assertIn('battery', expectations['modules'])


class KernelConfigTests(unittest.TestCase):
    def test_parses_set_and_not_set_lines(self):
        text = (
            "CONFIG_IWLWIFI=m\n"
            "CONFIG_IWLMVM=m\n"
            "# CONFIG_ATH12K is not set\n"
            "CONFIG_LOCALVERSION=\"\"\n"
        )
        values = inspect_image.parse_kernel_config(text)
        self.assertEqual(values['CONFIG_IWLWIFI'], 'm')
        self.assertEqual(values['CONFIG_ATH12K'], 'n')
        self.assertIn('CONFIG_LOCALVERSION', values)


class BootloaderParsingTests(unittest.TestCase):
    def test_parses_syslinux_labels(self):
        text = (
            "SERIAL 0 115200\nTIMEOUT 30\nPROMPT 1\nDEFAULT live\n"
            "\nLABEL live\n KERNEL /boot/vmlinuz-lts\n INITRD /boot/initramfs-lts\n"
            " APPEND modules=loop,squashfs quiet\n"
        )
        entries = inspect_image.parse_syslinux_cfg(text)
        self.assertEqual(len(entries), 1)
        self.assertEqual(entries[0]['label'], 'live')
        self.assertEqual(entries[0]['kernel'], '/boot/vmlinuz-lts')
        self.assertEqual(entries[0]['initrd'], '/boot/initramfs-lts')
        self.assertIn('modules=loop,squashfs', entries[0]['append'])

    def test_parses_grub_menuentries(self):
        text = (
            'set timeout=3\nset default=0\n'
            'menuentry "AIOS live" {\n'
            ' linux /boot/vmlinuz-lts modules=loop,squashfs quiet\n'
            ' initrd /boot/initramfs-lts\n'
            '}\n'
        )
        entries = inspect_image.parse_grub_cfg(text)
        self.assertEqual(len(entries), 1)
        self.assertEqual(entries[0]['title'], 'AIOS live')
        self.assertEqual(entries[0]['initrd'], '/boot/initramfs-lts')


class ModloopLayoutTests(unittest.TestCase):
    """Alpine's modloop keeps modules and firmware under modules/, not lib/."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.base = Path(self.tmp.name)

    def test_alpine_modloop_layout_is_found(self):
        modloop = self.base / 'alpine'
        (modloop / 'modules' / KERNEL_VERSION).mkdir(parents=True)
        (modloop / 'modules' / 'firmware' / 'iwlwifi').mkdir(parents=True)
        self.assertEqual(inspect_image.find_modules_root(modloop), modloop / 'modules')
        self.assertEqual(
            inspect_image.find_firmware_root(modloop), modloop / 'modules' / 'firmware')

    def test_firmware_directory_is_not_mistaken_for_a_kernel_version(self):
        modloop = self.base / 'only-firmware'
        (modloop / 'modules' / 'firmware').mkdir(parents=True)
        self.assertIsNone(inspect_image.find_modules_root(modloop))
        self.assertEqual(inspect_image.section_modloop(modloop)['status'], 'unavailable')

    def test_rootfs_style_lib_layout_is_still_accepted(self):
        rootfs = self.base / 'rootfs'
        (rootfs / 'lib' / 'modules' / KERNEL_VERSION).mkdir(parents=True)
        (rootfs / 'lib' / 'firmware').mkdir(parents=True)
        self.assertEqual(inspect_image.find_modules_root(rootfs), rootfs / 'lib' / 'modules')
        self.assertEqual(inspect_image.find_firmware_root(rootfs), rootfs / 'lib' / 'firmware')


class FullReportFixture(unittest.TestCase):
    """Builds a minimal but complete extracted-ISO fixture and inspects it."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name) / 'root'
        self.root.mkdir()

        # APK closure: two real files with deterministic content.
        self.apks_dir = self.root / 'apks' / 'x86_64'
        self.apks_dir.mkdir(parents=True)
        (self.apks_dir / 'busybox-1.36.1-r15.apk').write_bytes(b'fake-busybox-apk-bytes')
        (self.apks_dir / 'mesa-dri-gallium-23.3.6-r0.apk').write_bytes(b'fake-mesa-apk-bytes')

        # apkovl.
        self.apkovl_path = self.root / 'aios.apkovl.tar.gz'
        build_apkovl(
            self.apkovl_path,
            world=['alpine-base', 'mesa-dri-gallium', 'networkmanager'],
            repositories=[CANONICAL_MAIN, CANONICAL_COMMUNITY],
            services={'sysinit': ['udev', 'modloop'], 'default': ['networkmanager']},
        )

        # boot/ artifacts.
        boot_dir = self.root / 'boot'
        boot_dir.mkdir()
        (boot_dir / f'config-{KERNEL_VERSION}').write_text(
            "CONFIG_IWLWIFI=m\nCONFIG_IWLMVM=m\n# CONFIG_ATH12K is not set\nCONFIG_DRM=y\n",
            encoding='utf-8',
        )
        initramfs_data = build_cpio_newc([
            ('init', b'#!/bin/sh\necho starting\n'),
            ('etc/mdev.conf', b'.* root:root 660\n'),
        ])
        (boot_dir / 'initramfs-lts').write_bytes(gzip.compress(initramfs_data))

        syslinux_dir = boot_dir / 'syslinux'
        syslinux_dir.mkdir()
        (syslinux_dir / 'syslinux.cfg').write_text(
            "DEFAULT live\n\nLABEL live\n KERNEL /boot/vmlinuz-lts\n"
            " INITRD /boot/initramfs-lts\n APPEND modules=loop,squashfs quiet\n",
            encoding='utf-8',
        )
        grub_dir = boot_dir / 'grub'
        grub_dir.mkdir()
        (grub_dir / 'grub.cfg').write_text(
            'menuentry "AIOS live" {\n'
            ' linux /boot/vmlinuz-lts modules=loop,squashfs quiet\n'
            ' initrd /boot/initramfs-lts\n}\n',
            encoding='utf-8',
        )

        # modloop-root: a pre-extracted modloop tree in Alpine's real layout
        # (modules/<version> and modules/firmware, not lib/*).
        self.modloop_root = Path(self.tmp.name) / 'modloop'
        modules_dir = self.modloop_root / 'modules' / KERNEL_VERSION
        modules_dir.mkdir(parents=True)
        (modules_dir / 'iwlwifi.ko.gz').write_bytes(b'fake-module-bytes')
        (modules_dir / 'unrelated.ko.gz').write_bytes(b'fake-module-bytes')
        (modules_dir / 'modules.alias').write_text(
            "alias pci:v00008086d00002725sv*sd*bc*sc*i* iwlwifi\n"
            "alias pci:v00008086d00002725sv*sd*bc*sc*i* iwlmvm\n"
            "alias usb:v0E8Dp7961d*dc*dsc*dp*ic*isc*ip*in* mt7921u\n"
            "alias usb:v1234p5678d* some_unrelated_driver\n",
            encoding='utf-8',
        )
        firmware_dir = self.modloop_root / 'modules' / 'firmware' / 'iwlwifi'
        firmware_dir.mkdir(parents=True)
        (firmware_dir / 'iwlwifi-ty-a0-gf-a0-89.ucode').write_bytes(b'fake-firmware-bytes')
        (firmware_dir / 'iwlwifi-ty-a0-gf-a0.ucode.zst').write_bytes(b'fake-compressed-firmware')
        obscure_dir = self.modloop_root / 'modules' / 'firmware' / 'obscure-vendor'
        obscure_dir.mkdir(parents=True)
        (obscure_dir / 'not-a-highlight.bin').write_bytes(b'fake-other-firmware')

        # coverage manifest fixture.
        self.coverage_manifest = Path(self.tmp.name) / 'hardware-coverage.json'
        self.coverage_manifest.write_text(json.dumps(coverage_fixture()), encoding='utf-8')

        # recorded build evidence.
        self.build_inputs = self.root / 'build-inputs.env'
        self.build_inputs.write_text(
            "# Effective build inputs recorded by distro/alpine/mkimage.sh.\n"
            "ALPINE_BRANCH=v3.23\nIMAGE=alpine:3.23@sha256:deadbeef\n"
            "APORTS_REF=abc123\nLLAMA_REF=def456\nWHISPER_REF=ghi789\n",
            encoding='utf-8',
        )
        self.build_manifest = self.root / 'aios.iso.build-manifest.json'
        self.write_manifest()

    # -- fixture helpers -------------------------------------------------

    def closure_records(self):
        records = []
        for apk in sorted(self.apks_dir.glob('*.apk')):
            data = apk.read_bytes()
            records.append({
                'filename': apk.name,
                'path': f'apks/x86_64/{apk.name}',
                'sha256': hashlib.sha256(data).hexdigest(),
                'size': len(data),
            })
        return records

    def make_build_manifest(self, repo_main=CANONICAL_MAIN, main_index_sha='a' * 64,
                            packages=None):
        if packages is None:
            packages = self.closure_records()
        return {
            'schema_version': 1,
            'kind': 'aios-build-manifest',
            'generated_utc': '2026-01-01T00:00:00Z',
            'build': {'arch': 'x86_64', 'release_tag': '20260101'},
            'source_pins': {
                'kind': 'immutable',
                'values': {
                    'ALPINE_BRANCH': 'v3.23',
                    'IMAGE': 'alpine:3.23@sha256:deadbeef',
                    'APORTS_REF': 'abc123',
                    'LLAMA_REF': 'def456',
                    'WHISPER_REF': 'ghi789',
                },
                'overrides': {},
            },
            'repository_indexes': {
                'arch': 'x86_64',
                'repositories': [
                    {
                        'role': 'main',
                        'url': repo_main,
                        'canonical_url': CANONICAL_MAIN,
                        'source': 'default' if repo_main == CANONICAL_MAIN else 'override',
                        'apkindex_url': f'{repo_main}/x86_64/APKINDEX.tar.gz',
                        'apkindex': {'status': 'recorded', 'sha256': main_index_sha, 'size': 10},
                    },
                    {
                        'role': 'community',
                        'url': CANONICAL_COMMUNITY,
                        'canonical_url': CANONICAL_COMMUNITY,
                        'source': 'default',
                        'apkindex_url': f'{CANONICAL_COMMUNITY}/x86_64/APKINDEX.tar.gz',
                        'apkindex': {'status': 'recorded', 'sha256': 'b' * 64, 'size': 11},
                    },
                ],
            },
            'output_closure': {
                'kind': 'exact-output-closure',
                'status': 'recorded',
                'apk_count': len(packages),
                'total_size': sum(entry['size'] for entry in packages),
                'packages': packages,
            },
            'artifacts': {'iso': {'status': 'recorded', 'sha256': 'c' * 64, 'filename': 'aios.iso'}},
            'kernel_identity': {'status': 'recorded', 'module_versions': [KERNEL_VERSION]},
            'reproducibility': {
                'byte_reproducible': False,
                'package_resolution': 'output-closure-recorded-repository-index-sampled',
                'notes': ['output closure recorded; repository index sampled'],
            },
        }

    def write_manifest(self, **kwargs):
        self.build_manifest.write_text(
            json.dumps(self.make_build_manifest(**kwargs)), encoding='utf-8')

    def run_tool(self, extra_args=()):
        args = [
            sys.executable, str(SCRIPT),
            '--root', str(self.root),
            '--modloop-root', str(self.modloop_root),
            '--build-inputs', str(self.build_inputs),
            '--repo-build-env', str(ROOT / 'distro' / 'alpine' / 'build.env'),
            '--build-manifest', str(self.build_manifest),
            '--coverage-manifest', str(self.coverage_manifest),
            *extra_args,
        ]
        result = subprocess.run(args, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, msg=result.stderr)
        return json.loads(result.stdout)

    # -- general ---------------------------------------------------------

    def test_all_sections_available_with_full_fixture(self):
        report = self.run_tool()
        for name, section in report['sections'].items():
            self.assertEqual(section['status'], 'available', msg=f'{name}: {section}')

    def test_packages_section_reports_real_hashes(self):
        report = self.run_tool()
        packages = report['sections']['packages']['packages']
        names = {entry['filename'] for entry in packages}
        self.assertEqual(names, {'busybox-1.36.1-r15.apk', 'mesa-dri-gallium-23.3.6-r0.apk'})
        for entry in packages:
            self.assertEqual(len(entry['sha256']), 64)

    def test_initramfs_lists_expected_entries(self):
        report = self.run_tool()
        entries = report['sections']['initramfs']['entries']
        self.assertEqual(sorted(entry['path'] for entry in entries), ['etc/mdev.conf', 'init'])

    def test_modloop_modules_are_found_in_the_alpine_layout(self):
        report = self.run_tool()
        modloop = report['sections']['modloop']
        self.assertTrue(modloop['modules_root'].replace('\\', '/').endswith('modloop/modules'))
        versions = {entry['kernel_version'] for entry in modloop['module_versions']}
        self.assertEqual(versions, {KERNEL_VERSION})

    # -- firmware --------------------------------------------------------

    def test_firmware_is_read_from_modules_firmware_and_fully_listed(self):
        report = self.run_tool()
        firmware = report['sections']['firmware']
        self.assertTrue(firmware['firmware_root'].replace('\\', '/').endswith('modules/firmware'))
        self.assertEqual({entry['path'] for entry in firmware['files']}, {
            'iwlwifi/iwlwifi-ty-a0-gf-a0-89.ucode',
            'iwlwifi/iwlwifi-ty-a0-gf-a0.ucode.zst',
            'obscure-vendor/not-a-highlight.bin',
        })
        self.assertEqual(firmware['file_count'], 3)

    def test_firmware_records_compression_and_symlink_fields(self):
        report = self.run_tool()
        by_path = {entry['path']: entry for entry in report['sections']['firmware']['files']}
        self.assertIsNone(by_path['iwlwifi/iwlwifi-ty-a0-gf-a0-89.ucode']['compressed'])
        self.assertEqual(by_path['iwlwifi/iwlwifi-ty-a0-gf-a0.ucode.zst']['compressed'], 'zstd')
        for entry in by_path.values():
            self.assertIn('is_symlink', entry)
            self.assertIn('symlink_target', entry)

    def test_firmware_symlink_targets_are_reported(self):
        link = self.modloop_root / 'modules' / 'firmware' / 'iwlwifi' / 'link.ucode'
        try:
            os.symlink('iwlwifi-ty-a0-gf-a0-89.ucode', link)
        except (OSError, NotImplementedError) as error:
            self.skipTest(f'symlinks unavailable on this platform: {error}')
        report = self.run_tool()
        by_path = {entry['path']: entry for entry in report['sections']['firmware']['files']}
        entry = by_path['iwlwifi/link.ucode']
        self.assertTrue(entry['is_symlink'])
        self.assertEqual(entry['symlink_target'], 'iwlwifi-ty-a0-gf-a0-89.ucode')

    def test_firmware_highlights_remain_a_subset_of_the_full_inventory(self):
        report = self.run_tool()
        firmware = report['sections']['firmware']
        highlight_paths = {entry['path'] for entry in firmware['highlights']}
        all_paths = {entry['path'] for entry in firmware['files']}
        self.assertTrue(highlight_paths.issubset(all_paths))
        self.assertNotIn('obscure-vendor/not-a-highlight.bin', highlight_paths)

    def test_lib_firmware_only_tree_reports_unavailable_firmware_root(self):
        legacy = Path(self.tmp.name) / 'no-firmware'
        (legacy / 'modules' / KERNEL_VERSION).mkdir(parents=True)
        section = inspect_image.section_firmware(legacy)
        self.assertEqual(section['status'], 'unavailable')
        self.assertIn('modules/firmware', section['reason'])

    # -- alias validation ------------------------------------------------

    def test_alias_validation_matches_manifest_ids(self):
        report = self.run_tool()
        result = report['sections']['module_aliases']['by_kernel_version'][KERNEL_VERSION]
        by_id = {device['id']: device for device in result['devices']}

        ax210 = by_id['intel-wifi-ax210']
        self.assertEqual(ax210['status'], 'matched')
        self.assertEqual(ax210['matched_modules'], ['iwlmvm', 'iwlwifi'])
        self.assertEqual(ax210['unexpected_modules'], [])
        self.assertEqual(ax210['probe'], 'pci:v00008086d00002725sv*sd*bc*sc*i*')

        mt7921u = by_id['mediatek-mt7921u']
        self.assertEqual(mt7921u['status'], 'matched')
        self.assertEqual(mt7921u['matched_modules'], ['mt7921u'])

    def test_alias_validation_reports_unmatched_ids(self):
        report = self.run_tool()
        result = report['sections']['module_aliases']['by_kernel_version'][KERNEL_VERSION]
        self.assertEqual({entry['id'] for entry in result['unmatched_ids']}, {'absent-device'})
        self.assertEqual(result['checked_id_count'], 3)
        self.assertEqual(result['matched_id_count'], 2)

    def test_alias_validation_reports_ambiguity(self):
        report = self.run_tool()
        result = report['sections']['module_aliases']['by_kernel_version'][KERNEL_VERSION]
        # 8086:2725 resolves to two modules in this fixture's modules.alias.
        self.assertIn('intel-wifi-ax210', {entry['id'] for entry in result['ambiguous_ids']})

    def test_alias_validation_flags_unexpected_module_matches(self):
        alias_file = self.modloop_root / 'modules' / KERNEL_VERSION / 'modules.alias'
        alias_file.write_text(
            "alias pci:v00008086d00002725sv*sd*bc*sc*i* surprise_driver\n", encoding='utf-8')
        report = self.run_tool()
        result = report['sections']['module_aliases']['by_kernel_version'][KERNEL_VERSION]
        by_id = {device['id']: device for device in result['devices']}
        self.assertEqual(by_id['intel-wifi-ax210']['unexpected_modules'], ['surprise_driver'])
        self.assertTrue(result['ambiguous_ids'])

    def test_alias_validation_keeps_relevant_aliases(self):
        report = self.run_tool()
        result = report['sections']['module_aliases']['by_kernel_version'][KERNEL_VERSION]
        modules = {entry['module'] for entry in result['relevant_aliases']}
        self.assertIn('iwlwifi', modules)
        self.assertNotIn('some_unrelated_driver', modules)

    def test_alias_section_defaults_to_the_repository_coverage_manifest(self):
        args = [
            sys.executable, str(SCRIPT),
            '--root', str(self.root),
            '--modloop-root', str(self.modloop_root),
        ]
        result = subprocess.run(args, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, msg=result.stderr)
        report = json.loads(result.stdout)
        used = report['inputs']['coverage_manifest'].replace('\\', '/')
        self.assertTrue(used.endswith('docs/qa/hardware-coverage.json'))
        section = report['sections']['module_aliases']
        self.assertEqual(section['status'], 'available')
        self.assertGreater(section['coverage_device_id_count'], 10)

    def test_alias_section_is_unavailable_without_a_coverage_manifest(self):
        missing = Path(self.tmp.name) / 'nope.json'
        section = self.run_tool(['--coverage-manifest', str(missing)])['sections']['module_aliases']
        self.assertEqual(section['status'], 'unavailable')
        self.assertIn('coverage manifest', section['reason'])

    # -- recorded inputs -------------------------------------------------

    def test_recorded_inputs_separates_the_three_kinds_of_evidence(self):
        recorded = self.run_tool()['sections']['recorded_inputs']
        self.assertEqual(recorded['source_pins']['kind'], 'source-selection')
        self.assertEqual(
            recorded['repository_indexes']['kind'],
            'post-build-moving-repository-index-sample',
        )
        self.assertEqual(recorded['output_closure']['kind'], 'exact-output-closure')
        self.assertFalse(recorded['reproducibility']['byte_reproducible'])
        self.assertEqual(
            recorded['reproducibility']['package_resolution'],
            'output-closure-recorded-repository-index-sampled',
        )

    def test_recorded_inputs_drift_detection(self):
        source_pins = self.run_tool()['sections']['recorded_inputs']['source_pins']
        # The fixture's build-inputs.env intentionally differs from the
        # checked-out distro/alpine/build.env (different IMAGE digest/refs),
        # so drift must be detected rather than silently ignored.
        self.assertFalse(source_pins['matches_current_repo_pins'])
        self.assertIn('IMAGE', source_pins['differences'])

    def test_repository_indexes_record_apkindex_digests(self):
        repos = self.run_tool()['sections']['recorded_inputs'][
            'repository_indexes']['repositories']
        by_role = {repo['role']: repo for repo in repos}
        self.assertEqual(by_role['main']['apkindex_status'], 'recorded')
        self.assertEqual(by_role['main']['apkindex_sha256'], 'a' * 64)
        self.assertTrue(by_role['main']['apkindex_url'].endswith('x86_64/APKINDEX.tar.gz'))

    def test_repository_override_is_visible(self):
        override = 'https://mirror.example.invalid/alpine/v3.23/main'
        self.write_manifest(repo_main=override)
        indexes = self.run_tool()['sections']['recorded_inputs']['repository_indexes']
        self.assertTrue(indexes['has_repository_overrides'])
        self.assertEqual(indexes['overridden_roles'], ['main'])
        drift = indexes['repository_url_drift_vs_current_build_env']
        self.assertIn('main', drift)
        self.assertEqual(drift['main']['recorded'], override)
        self.assertEqual(drift['main']['expected_for_current_branch'], CANONICAL_MAIN)

    def test_default_repositories_are_not_reported_as_overrides(self):
        indexes = self.run_tool()['sections']['recorded_inputs']['repository_indexes']
        self.assertFalse(indexes['has_repository_overrides'])
        self.assertEqual(indexes['repository_url_drift_vs_current_build_env'], {})

    def test_apkindex_drift_between_two_builds_is_reported(self):
        other = self.root / 'other.build-manifest.json'
        other.write_text(json.dumps(self.make_build_manifest(main_index_sha='d' * 64)),
                         encoding='utf-8')
        drift = self.run_tool(['--compare-build-manifest', str(other)])['sections'][
            'recorded_inputs']['repository_indexes']['apkindex_drift_vs_compared_build']
        self.assertTrue(drift['main']['changed'])
        self.assertFalse(drift['community']['changed'])

    def test_missing_apkindex_digest_is_reported_not_hidden(self):
        manifest = self.make_build_manifest()
        manifest['repository_indexes']['repositories'][0]['apkindex'] = {
            'status': 'unavailable', 'reason': 'URLError: offline build'}
        self.build_manifest.write_text(json.dumps(manifest), encoding='utf-8')
        indexes = self.run_tool()['sections']['recorded_inputs']['repository_indexes']
        self.assertEqual(indexes['roles_without_recorded_index'], ['main'])
        by_role = {repo['role']: repo for repo in indexes['repositories']}
        self.assertIn('offline build', by_role['main']['apkindex_reason'])

    def test_output_closure_is_verified_against_the_image(self):
        closure = self.run_tool()['sections']['recorded_inputs']['output_closure']
        self.assertTrue(closure['verified_against_image'])
        self.assertTrue(closure['closure_matches_image'])
        self.assertEqual(closure['missing_from_image'], [])
        self.assertEqual(closure['unexpected_in_image'], [])
        self.assertEqual(closure['sha256_mismatches'], [])
        self.assertEqual(closure['recorded_apk_count'], 2)

    def test_output_closure_detects_a_tampered_package(self):
        records = self.closure_records()
        records[0]['sha256'] = 'f' * 64
        self.write_manifest(packages=records)
        closure = self.run_tool()['sections']['recorded_inputs']['output_closure']
        self.assertFalse(closure['closure_matches_image'])
        self.assertEqual([m['filename'] for m in closure['sha256_mismatches']],
                         [records[0]['filename']])

    def test_output_closure_detects_missing_and_extra_packages(self):
        records = self.closure_records()
        records.append({'filename': 'ghost-1.0-r0.apk', 'path': 'apks/x86_64/ghost-1.0-r0.apk',
                        'sha256': 'e' * 64, 'size': 1})
        self.write_manifest(packages=records)
        (self.apks_dir / 'extra-9.9-r9.apk').write_bytes(b'unexpected')
        closure = self.run_tool()['sections']['recorded_inputs']['output_closure']
        self.assertEqual(closure['missing_from_image'], ['ghost-1.0-r0.apk'])
        self.assertEqual(closure['unexpected_in_image'], ['extra-9.9-r9.apk'])
        self.assertFalse(closure['closure_matches_image'])

    def test_closure_drift_between_two_builds_is_reported(self):
        records = self.closure_records()
        records[0] = dict(records[0], sha256='9' * 64)
        other = self.root / 'other.build-manifest.json'
        other.write_text(json.dumps(self.make_build_manifest(packages=records)), encoding='utf-8')
        drift = self.run_tool(['--compare-build-manifest', str(other)])['sections'][
            'recorded_inputs']['output_closure']['closure_drift_vs_compared_build']
        self.assertFalse(drift['identical'])
        self.assertEqual(drift['changed_sha256'], [records[0]['filename']])

    def test_recorded_inputs_without_a_build_manifest_is_explicit(self):
        args = [
            sys.executable, str(SCRIPT),
            '--root', str(self.root),
            '--build-inputs', str(self.build_inputs),
        ]
        result = subprocess.run(args, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, msg=result.stderr)
        recorded = json.loads(result.stdout)['sections']['recorded_inputs']
        self.assertEqual(recorded['status'], 'available')
        self.assertEqual(recorded['repository_indexes']['status'], 'unavailable')
        self.assertEqual(recorded['output_closure']['status'], 'unavailable')

    def test_services_and_bootloader_sections(self):
        report = self.run_tool()
        services = report['sections']['services']['services_by_runlevel']
        self.assertIn('udev', services['sysinit'])
        self.assertIn('networkmanager', services['default'])
        bootloader = report['sections']['bootloader']
        self.assertEqual(bootloader['syslinux'][0]['label'], 'live')
        self.assertEqual(bootloader['grub'][0]['title'], 'AIOS live')

    def test_report_is_deterministic_across_runs(self):
        self.assertEqual(self.run_tool(), self.run_tool())

    def test_missing_modloop_reports_unavailable_not_fabricated(self):
        args = [
            sys.executable, str(SCRIPT),
            '--root', str(self.root),
            '--build-inputs', str(self.build_inputs),
        ]
        result = subprocess.run(args, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, msg=result.stderr)
        report = json.loads(result.stdout)
        for name in ('modloop', 'module_aliases', 'firmware'):
            section = report['sections'][name]
            self.assertEqual(section['status'], 'unavailable')
            self.assertTrue(section['reason'])

    def test_missing_root_artifacts_are_unavailable(self):
        empty_root = Path(self.tmp.name) / 'empty-root'
        empty_root.mkdir()
        args = [sys.executable, str(SCRIPT), '--root', str(empty_root)]
        result = subprocess.run(args, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, msg=result.stderr)
        report = json.loads(result.stdout)
        for name in ('packages', 'kernel', 'initramfs', 'modloop', 'module_aliases',
                     'firmware', 'mesa_userspace', 'bootloader', 'services', 'recorded_inputs'):
            self.assertEqual(report['sections'][name]['status'], 'unavailable', msg=name)


if __name__ == '__main__':
    unittest.main()
