permit nopass aios as root cmd /sbin/poweroff args
permit nopass aios as root cmd /sbin/reboot args
permit nopass aios as root cmd /usr/local/sbin/aios-install args
permit nopass aios as root cmd /usr/local/sbin/aios-clock args
permit nopass aios as root cmd /usr/local/sbin/aios-regdomain args
